name: ticketsales
description: "A ticket sales flutter project"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  sqflite_common_ffi: ^2.3.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true